server:
  port: 8082

spring:
  application:
    name: produits
  datasource:
    url: ${DB_URL:jdbc:h2:mem:produits;DB_CLOSE_DELAY=-1}
    username: ${DB_USER:sa}
    password: ${DB_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
